<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 5.0.2
 */

/**
 * Database `wilayah`
 */

/* `wilayah`.`t_kota` */
$t_kota = array(
  array('id' => '1101','nama' => 'KAB. ACEH SELATAN'),
  array('id' => '1102','nama' => 'KAB. ACEH TENGGARA'),
  array('id' => '1103','nama' => 'KAB. ACEH TIMUR'),
  array('id' => '1104','nama' => 'KAB. ACEH TENGAH'),
  array('id' => '1105','nama' => 'KAB. ACEH BARAT'),
  array('id' => '1106','nama' => 'KAB. ACEH BESAR'),
  array('id' => '1107','nama' => 'KAB. PIDIE'),
  array('id' => '1108','nama' => 'KAB. ACEH UTARA'),
  array('id' => '1109','nama' => 'KAB. SIMEULUE'),
  array('id' => '1110','nama' => 'KAB. ACEH SINGKIL'),
  array('id' => '1111','nama' => 'KAB. BIREUEN'),
  array('id' => '1112','nama' => 'KAB. ACEH BARAT DAYA'),
  array('id' => '1113','nama' => 'KAB. GAYO LUES'),
  array('id' => '1114','nama' => 'KAB. ACEH JAYA'),
  array('id' => '1115','nama' => 'KAB. NAGAN RAYA'),
  array('id' => '1116','nama' => 'KAB. ACEH TAMIANG'),
  array('id' => '1117','nama' => 'KAB. BENER MERIAH'),
  array('id' => '1118','nama' => 'KAB. PIDIE JAYA'),
  array('id' => '1171','nama' => 'KOTA BANDA ACEH'),
  array('id' => '1172','nama' => 'KOTA SABANG'),
  array('id' => '1173','nama' => 'KOTA LHOKSEUMAWE'),
  array('id' => '1174','nama' => 'KOTA LANGSA'),
  array('id' => '1175','nama' => 'KOTA SUBULUSSALAM'),
  array('id' => '1201','nama' => 'KAB. TAPANULI TENGAH'),
  array('id' => '1202','nama' => 'KAB. TAPANULI UTARA'),
  array('id' => '1203','nama' => 'KAB. TAPANULI SELATAN'),
  array('id' => '1204','nama' => 'KAB. NIAS'),
  array('id' => '1205','nama' => 'KAB. LANGKAT'),
  array('id' => '1206','nama' => 'KAB. KARO'),
  array('id' => '1207','nama' => 'KAB. DELI SERDANG'),
  array('id' => '1208','nama' => 'KAB. SIMALUNGUN'),
  array('id' => '1209','nama' => 'KAB. ASAHAN'),
  array('id' => '1210','nama' => 'KAB. LABUHANBATU'),
  array('id' => '1211','nama' => 'KAB. DAIRI'),
  array('id' => '1212','nama' => 'KAB. TOBA SAMOSIR'),
  array('id' => '1213','nama' => 'KAB. MANDAILING NATAL'),
  array('id' => '1214','nama' => 'KAB. NIAS SELATAN'),
  array('id' => '1215','nama' => 'KAB. PAKPAK BHARAT'),
  array('id' => '1216','nama' => 'KAB. HUMBANG HASUNDUTAN'),
  array('id' => '1217','nama' => 'KAB. SAMOSIR'),
  array('id' => '1218','nama' => 'KAB. SERDANG BEDAGAI'),
  array('id' => '1219','nama' => 'KAB. BATU BARA'),
  array('id' => '1220','nama' => 'KAB. PADANG LAWAS UTARA'),
  array('id' => '1221','nama' => 'KAB. PADANG LAWAS'),
  array('id' => '1222','nama' => 'KAB. LABUHANBATU SELATAN'),
  array('id' => '1223','nama' => 'KAB. LABUHANBATU UTARA'),
  array('id' => '1224','nama' => 'KAB. NIAS UTARA'),
  array('id' => '1225','nama' => 'KAB. NIAS BARAT'),
  array('id' => '1271','nama' => 'KOTA MEDAN'),
  array('id' => '1272','nama' => 'KOTA PEMATANGSIANTAR'),
  array('id' => '1273','nama' => 'KOTA SIBOLGA'),
  array('id' => '1274','nama' => 'KOTA TANJUNG BALAI'),
  array('id' => '1275','nama' => 'KOTA BINJAI'),
  array('id' => '1276','nama' => 'KOTA TEBING TINGGI'),
  array('id' => '1277','nama' => 'KOTA PADANGSIDIMPUAN'),
  array('id' => '1278','nama' => 'KOTA GUNUNGSITOLI'),
  array('id' => '1301','nama' => 'KAB. PESISIR SELATAN'),
  array('id' => '1302','nama' => 'KAB. SOLOK'),
  array('id' => '1303','nama' => 'KAB. SIJUNJUNG'),
  array('id' => '1304','nama' => 'KAB. TANAH DATAR'),
  array('id' => '1305','nama' => 'KAB. PADANG PARIAMAN'),
  array('id' => '1306','nama' => 'KAB. AGAM'),
  array('id' => '1307','nama' => 'KAB. LIMA PULUH KOTA'),
  array('id' => '1308','nama' => 'KAB. PASAMAN'),
  array('id' => '1309','nama' => 'KAB. KEPULAUAN MENTAWAI'),
  array('id' => '1310','nama' => 'KAB. DHARMASRAYA'),
  array('id' => '1311','nama' => 'KAB. SOLOK SELATAN'),
  array('id' => '1312','nama' => 'KAB. PASAMAN BARAT'),
  array('id' => '1371','nama' => 'KOTA PADANG'),
  array('id' => '1372','nama' => 'KOTA SOLOK'),
  array('id' => '1373','nama' => 'KOTA SAWAHLUNTO'),
  array('id' => '1374','nama' => 'KOTA PADANG PANJANG'),
  array('id' => '1375','nama' => 'KOTA BUKITTINGGI'),
  array('id' => '1376','nama' => 'KOTA PAYAKUMBUH'),
  array('id' => '1377','nama' => 'KOTA PARIAMAN'),
  array('id' => '1401','nama' => 'KAB. KAMPAR'),
  array('id' => '1402','nama' => 'KAB. INDRAGIRI HULU'),
  array('id' => '1403','nama' => 'KAB. BENGKALIS'),
  array('id' => '1404','nama' => 'KAB. INDRAGIRI HILIR'),
  array('id' => '1405','nama' => 'KAB. PELALAWAN'),
  array('id' => '1406','nama' => 'KAB. ROKAN HULU'),
  array('id' => '1407','nama' => 'KAB. ROKAN HILIR'),
  array('id' => '1408','nama' => 'KAB. SIAK'),
  array('id' => '1409','nama' => 'KAB. KUANTAN SINGINGI'),
  array('id' => '1410','nama' => 'KAB. KEPULAUAN MERANTI'),
  array('id' => '1471','nama' => 'KOTA PEKANBARU'),
  array('id' => '1472','nama' => 'KOTA DUMAI'),
  array('id' => '1501','nama' => 'KAB. KERINCI'),
  array('id' => '1502','nama' => 'KAB. MERANGIN'),
  array('id' => '1503','nama' => 'KAB. SAROLANGUN'),
  array('id' => '1504','nama' => 'KAB. BATANGHARI'),
  array('id' => '1505','nama' => 'KAB. MUARO JAMBI'),
  array('id' => '1506','nama' => 'KAB. TANJUNG JABUNG BARAT'),
  array('id' => '1507','nama' => 'KAB. TANJUNG JABUNG TIMUR'),
  array('id' => '1508','nama' => 'KAB. BUNGO'),
  array('id' => '1509','nama' => 'KAB. TEBO'),
  array('id' => '1571','nama' => 'KOTA JAMBI'),
  array('id' => '1572','nama' => 'KOTA SUNGAI PENUH'),
  array('id' => '1601','nama' => 'KAB. OGAN KOMERING ULU'),
  array('id' => '1602','nama' => 'KAB. OGAN KOMERING ILIR'),
  array('id' => '1603','nama' => 'KAB. MUARA ENIM'),
  array('id' => '1604','nama' => 'KAB. LAHAT'),
  array('id' => '1605','nama' => 'KAB. MUSI RAWAS'),
  array('id' => '1606','nama' => 'KAB. MUSI BANYUASIN'),
  array('id' => '1607','nama' => 'KAB. BANYUASIN'),
  array('id' => '1608','nama' => 'KAB. OGAN KOMERING ULU TIMUR'),
  array('id' => '1609','nama' => 'KAB. OGAN KOMERING ULU SELATAN'),
  array('id' => '1610','nama' => 'KAB. OGAN ILIR'),
  array('id' => '1611','nama' => 'KAB. EMPAT LAWANG'),
  array('id' => '1612','nama' => 'KAB. PENUKAL ABAB LEMATANG ILIR'),
  array('id' => '1613','nama' => 'KAB. MUSI RAWAS UTARA'),
  array('id' => '1671','nama' => 'KOTA PALEMBANG'),
  array('id' => '1672','nama' => 'KOTA PAGAR ALAM'),
  array('id' => '1673','nama' => 'KOTA LUBUK LINGGAU'),
  array('id' => '1674','nama' => 'KOTA PRABUMULIH'),
  array('id' => '1701','nama' => 'KAB. BENGKULU SELATAN'),
  array('id' => '1702','nama' => 'KAB. REJANG LEBONG'),
  array('id' => '1703','nama' => 'KAB. BENGKULU UTARA'),
  array('id' => '1704','nama' => 'KAB. KAUR'),
  array('id' => '1705','nama' => 'KAB. SELUMA'),
  array('id' => '1706','nama' => 'KAB. MUKO MUKO'),
  array('id' => '1707','nama' => 'KAB. LEBONG'),
  array('id' => '1708','nama' => 'KAB. KEPAHIANG'),
  array('id' => '1709','nama' => 'KAB. BENGKULU TENGAH'),
  array('id' => '1771','nama' => 'KOTA BENGKULU'),
  array('id' => '1801','nama' => 'KAB. LAMPUNG SELATAN'),
  array('id' => '1802','nama' => 'KAB. LAMPUNG TENGAH'),
  array('id' => '1803','nama' => 'KAB. LAMPUNG UTARA'),
  array('id' => '1804','nama' => 'KAB. LAMPUNG BARAT'),
  array('id' => '1805','nama' => 'KAB. TULANG BAWANG'),
  array('id' => '1806','nama' => 'KAB. TANGGAMUS'),
  array('id' => '1807','nama' => 'KAB. LAMPUNG TIMUR'),
  array('id' => '1808','nama' => 'KAB. WAY KANAN'),
  array('id' => '1809','nama' => 'KAB. PESAWARAN'),
  array('id' => '1810','nama' => 'KAB. PRINGSEWU'),
  array('id' => '1811','nama' => 'KAB. MESUJI'),
  array('id' => '1812','nama' => 'KAB. TULANG BAWANG BARAT'),
  array('id' => '1813','nama' => 'KAB. PESISIR BARAT'),
  array('id' => '1871','nama' => 'KOTA BANDAR LAMPUNG'),
  array('id' => '1872','nama' => 'KOTA METRO'),
  array('id' => '1901','nama' => 'KAB. BANGKA'),
  array('id' => '1902','nama' => 'KAB. BELITUNG'),
  array('id' => '1903','nama' => 'KAB. BANGKA SELATAN'),
  array('id' => '1904','nama' => 'KAB. BANGKA TENGAH'),
  array('id' => '1905','nama' => 'KAB. BANGKA BARAT'),
  array('id' => '1906','nama' => 'KAB. BELITUNG TIMUR'),
  array('id' => '1971','nama' => 'KOTA PANGKAL PINANG'),
  array('id' => '2101','nama' => 'KAB. BINTAN'),
  array('id' => '2102','nama' => 'KAB. KARIMUN'),
  array('id' => '2103','nama' => 'KAB. NATUNA'),
  array('id' => '2104','nama' => 'KAB. LINGGA'),
  array('id' => '2105','nama' => 'KAB. KEPULAUAN ANAMBAS'),
  array('id' => '2171','nama' => 'KOTA BATAM'),
  array('id' => '2172','nama' => 'KOTA TANJUNG PINANG'),
  array('id' => '3101','nama' => 'KAB. ADM. KEP. SERIBU'),
  array('id' => '3171','nama' => 'KOTA ADM. JAKARTA PUSAT'),
  array('id' => '3172','nama' => 'KOTA ADM. JAKARTA UTARA'),
  array('id' => '3173','nama' => 'KOTA ADM. JAKARTA BARAT'),
  array('id' => '3174','nama' => 'KOTA ADM. JAKARTA SELATAN'),
  array('id' => '3175','nama' => 'KOTA ADM. JAKARTA TIMUR'),
  array('id' => '3201','nama' => 'KAB. BOGOR'),
  array('id' => '3202','nama' => 'KAB. SUKABUMI'),
  array('id' => '3203','nama' => 'KAB. CIANJUR'),
  array('id' => '3204','nama' => 'KAB. BANDUNG'),
  array('id' => '3205','nama' => 'KAB. GARUT'),
  array('id' => '3206','nama' => 'KAB. TASIKMALAYA'),
  array('id' => '3207','nama' => 'KAB. CIAMIS'),
  array('id' => '3208','nama' => 'KAB. KUNINGAN'),
  array('id' => '3209','nama' => 'KAB. CIREBON'),
  array('id' => '3210','nama' => 'KAB. MAJALENGKA'),
  array('id' => '3211','nama' => 'KAB. SUMEDANG'),
  array('id' => '3212','nama' => 'KAB. INDRAMAYU'),
  array('id' => '3213','nama' => 'KAB. SUBANG'),
  array('id' => '3214','nama' => 'KAB. PURWAKARTA'),
  array('id' => '3215','nama' => 'KAB. KARAWANG'),
  array('id' => '3216','nama' => 'KAB. BEKASI'),
  array('id' => '3217','nama' => 'KAB. BANDUNG BARAT'),
  array('id' => '3218','nama' => 'KAB. PANGANDARAN'),
  array('id' => '3271','nama' => 'KOTA BOGOR'),
  array('id' => '3272','nama' => 'KOTA SUKABUMI'),
  array('id' => '3273','nama' => 'KOTA BANDUNG'),
  array('id' => '3274','nama' => 'KOTA CIREBON'),
  array('id' => '3275','nama' => 'KOTA BEKASI'),
  array('id' => '3276','nama' => 'KOTA DEPOK'),
  array('id' => '3277','nama' => 'KOTA CIMAHI'),
  array('id' => '3278','nama' => 'KOTA TASIKMALAYA'),
  array('id' => '3279','nama' => 'KOTA BANJAR'),
  array('id' => '3301','nama' => 'KAB. CILACAP'),
  array('id' => '3302','nama' => 'KAB. BANYUMAS'),
  array('id' => '3303','nama' => 'KAB. PURBALINGGA'),
  array('id' => '3304','nama' => 'KAB. BANJARNEGARA'),
  array('id' => '3305','nama' => 'KAB. KEBUMEN'),
  array('id' => '3306','nama' => 'KAB. PURWOREJO'),
  array('id' => '3307','nama' => 'KAB. WONOSOBO'),
  array('id' => '3308','nama' => 'KAB. MAGELANG'),
  array('id' => '3309','nama' => 'KAB. BOYOLALI'),
  array('id' => '3310','nama' => 'KAB. KLATEN'),
  array('id' => '3311','nama' => 'KAB. SUKOHARJO'),
  array('id' => '3312','nama' => 'KAB. WONOGIRI'),
  array('id' => '3313','nama' => 'KAB. KARANGANYAR'),
  array('id' => '3314','nama' => 'KAB. SRAGEN'),
  array('id' => '3315','nama' => 'KAB. GROBOGAN'),
  array('id' => '3316','nama' => 'KAB. BLORA'),
  array('id' => '3317','nama' => 'KAB. REMBANG'),
  array('id' => '3318','nama' => 'KAB. PATI'),
  array('id' => '3319','nama' => 'KAB. KUDUS'),
  array('id' => '3320','nama' => 'KAB. JEPARA'),
  array('id' => '3321','nama' => 'KAB. DEMAK'),
  array('id' => '3322','nama' => 'KAB. SEMARANG'),
  array('id' => '3323','nama' => 'KAB. TEMANGGUNG'),
  array('id' => '3324','nama' => 'KAB. KENDAL'),
  array('id' => '3325','nama' => 'KAB. BATANG'),
  array('id' => '3326','nama' => 'KAB. PEKALONGAN'),
  array('id' => '3327','nama' => 'KAB. PEMALANG'),
  array('id' => '3328','nama' => 'KAB. TEGAL'),
  array('id' => '3329','nama' => 'KAB. BREBES'),
  array('id' => '3371','nama' => 'KOTA MAGELANG'),
  array('id' => '3372','nama' => 'KOTA SURAKARTA'),
  array('id' => '3373','nama' => 'KOTA SALATIGA'),
  array('id' => '3374','nama' => 'KOTA SEMARANG'),
  array('id' => '3375','nama' => 'KOTA PEKALONGAN'),
  array('id' => '3376','nama' => 'KOTA TEGAL'),
  array('id' => '3401','nama' => 'KAB. KULON PROGO'),
  array('id' => '3402','nama' => 'KAB. BANTUL'),
  array('id' => '3403','nama' => 'KAB. GUNUNGKIDUL'),
  array('id' => '3404','nama' => 'KAB. SLEMAN'),
  array('id' => '3471','nama' => 'KOTA YOGYAKARTA'),
  array('id' => '3501','nama' => 'KAB. PACITAN'),
  array('id' => '3502','nama' => 'KAB. PONOROGO'),
  array('id' => '3503','nama' => 'KAB. TRENGGALEK'),
  array('id' => '3504','nama' => 'KAB. TULUNGAGUNG'),
  array('id' => '3505','nama' => 'KAB. BLITAR'),
  array('id' => '3506','nama' => 'KAB. KEDIRI'),
  array('id' => '3507','nama' => 'KAB. MALANG'),
  array('id' => '3508','nama' => 'KAB. LUMAJANG'),
  array('id' => '3509','nama' => 'KAB. JEMBER'),
  array('id' => '3510','nama' => 'KAB. BANYUWANGI'),
  array('id' => '3511','nama' => 'KAB. BONDOWOSO'),
  array('id' => '3512','nama' => 'KAB. SITUBONDO'),
  array('id' => '3513','nama' => 'KAB. PROBOLINGGO'),
  array('id' => '3514','nama' => 'KAB. PASURUAN'),
  array('id' => '3515','nama' => 'KAB. SIDOARJO'),
  array('id' => '3516','nama' => 'KAB. MOJOKERTO'),
  array('id' => '3517','nama' => 'KAB. JOMBANG'),
  array('id' => '3518','nama' => 'KAB. NGANJUK'),
  array('id' => '3519','nama' => 'KAB. MADIUN'),
  array('id' => '3520','nama' => 'KAB. MAGETAN'),
  array('id' => '3521','nama' => 'KAB. NGAWI'),
  array('id' => '3522','nama' => 'KAB. BOJONEGORO'),
  array('id' => '3523','nama' => 'KAB. TUBAN'),
  array('id' => '3524','nama' => 'KAB. LAMONGAN'),
  array('id' => '3525','nama' => 'KAB. GRESIK'),
  array('id' => '3526','nama' => 'KAB. BANGKALAN'),
  array('id' => '3527','nama' => 'KAB. SAMPANG'),
  array('id' => '3528','nama' => 'KAB. PAMEKASAN'),
  array('id' => '3529','nama' => 'KAB. SUMENEP'),
  array('id' => '3571','nama' => 'KOTA KEDIRI'),
  array('id' => '3572','nama' => 'KOTA BLITAR'),
  array('id' => '3573','nama' => 'KOTA MALANG'),
  array('id' => '3574','nama' => 'KOTA PROBOLINGGO'),
  array('id' => '3575','nama' => 'KOTA PASURUAN'),
  array('id' => '3576','nama' => 'KOTA MOJOKERTO'),
  array('id' => '3577','nama' => 'KOTA MADIUN'),
  array('id' => '3578','nama' => 'KOTA SURABAYA'),
  array('id' => '3579','nama' => 'KOTA BATU'),
  array('id' => '3601','nama' => 'KAB. PANDEGLANG'),
  array('id' => '3602','nama' => 'KAB. LEBAK'),
  array('id' => '3603','nama' => 'KAB. TANGERANG'),
  array('id' => '3604','nama' => 'KAB. SERANG'),
  array('id' => '3671','nama' => 'KOTA TANGERANG'),
  array('id' => '3672','nama' => 'KOTA CILEGON'),
  array('id' => '3673','nama' => 'KOTA SERANG'),
  array('id' => '3674','nama' => 'KOTA TANGERANG SELATAN'),
  array('id' => '5101','nama' => 'KAB. JEMBRANA'),
  array('id' => '5102','nama' => 'KAB. TABANAN'),
  array('id' => '5103','nama' => 'KAB. BADUNG'),
  array('id' => '5104','nama' => 'KAB. GIANYAR'),
  array('id' => '5105','nama' => 'KAB. KLUNGKUNG'),
  array('id' => '5106','nama' => 'KAB. BANGLI'),
  array('id' => '5107','nama' => 'KAB. KARANGASEM'),
  array('id' => '5108','nama' => 'KAB. BULELENG'),
  array('id' => '5171','nama' => 'KOTA DENPASAR'),
  array('id' => '5201','nama' => 'KAB. LOMBOK BARAT'),
  array('id' => '5202','nama' => 'KAB. LOMBOK TENGAH'),
  array('id' => '5203','nama' => 'KAB. LOMBOK TIMUR'),
  array('id' => '5204','nama' => 'KAB. SUMBAWA'),
  array('id' => '5205','nama' => 'KAB. DOMPU'),
  array('id' => '5206','nama' => 'KAB. BIMA'),
  array('id' => '5207','nama' => 'KAB. SUMBAWA BARAT'),
  array('id' => '5208','nama' => 'KAB. LOMBOK UTARA'),
  array('id' => '5271','nama' => 'KOTA MATARAM'),
  array('id' => '5272','nama' => 'KOTA BIMA'),
  array('id' => '5301','nama' => 'KAB. KUPANG'),
  array('id' => '5302','nama' => 'KAB TIMOR TENGAH SELATAN'),
  array('id' => '5303','nama' => 'KAB. TIMOR TENGAH UTARA'),
  array('id' => '5304','nama' => 'KAB. BELU'),
  array('id' => '5305','nama' => 'KAB. ALOR'),
  array('id' => '5306','nama' => 'KAB. FLORES TIMUR'),
  array('id' => '5307','nama' => 'KAB. SIKKA'),
  array('id' => '5308','nama' => 'KAB. ENDE'),
  array('id' => '5309','nama' => 'KAB. NGADA'),
  array('id' => '5310','nama' => 'KAB. MANGGARAI'),
  array('id' => '5311','nama' => 'KAB. SUMBA TIMUR'),
  array('id' => '5312','nama' => 'KAB. SUMBA BARAT'),
  array('id' => '5313','nama' => 'KAB. LEMBATA'),
  array('id' => '5314','nama' => 'KAB. ROTE NDAO'),
  array('id' => '5315','nama' => 'KAB. MANGGARAI BARAT'),
  array('id' => '5316','nama' => 'KAB. NAGEKEO'),
  array('id' => '5317','nama' => 'KAB. SUMBA TENGAH'),
  array('id' => '5318','nama' => 'KAB. SUMBA BARAT DAYA'),
  array('id' => '5319','nama' => 'KAB. MANGGARAI TIMUR'),
  array('id' => '5320','nama' => 'KAB. SABU RAIJUA'),
  array('id' => '5321','nama' => 'KAB. MALAKA'),
  array('id' => '5371','nama' => 'KOTA KUPANG'),
  array('id' => '6101','nama' => 'KAB. SAMBAS'),
  array('id' => '6102','nama' => 'KAB. MEMPAWAH'),
  array('id' => '6103','nama' => 'KAB. SANGGAU'),
  array('id' => '6104','nama' => 'KAB. KETAPANG'),
  array('id' => '6105','nama' => 'KAB. SINTANG'),
  array('id' => '6106','nama' => 'KAB. KAPUAS HULU'),
  array('id' => '6107','nama' => 'KAB. BENGKAYANG'),
  array('id' => '6108','nama' => 'KAB. LANDAK'),
  array('id' => '6109','nama' => 'KAB. SEKADAU'),
  array('id' => '6110','nama' => 'KAB. MELAWI'),
  array('id' => '6111','nama' => 'KAB. KAYONG UTARA'),
  array('id' => '6112','nama' => 'KAB. KUBU RAYA'),
  array('id' => '6171','nama' => 'KOTA PONTIANAK'),
  array('id' => '6172','nama' => 'KOTA SINGKAWANG'),
  array('id' => '6201','nama' => 'KAB. KOTAWARINGIN BARAT'),
  array('id' => '6202','nama' => 'KAB. KOTAWARINGIN TIMUR'),
  array('id' => '6203','nama' => 'KAB. KAPUAS'),
  array('id' => '6204','nama' => 'KAB. BARITO SELATAN'),
  array('id' => '6205','nama' => 'KAB. BARITO UTARA'),
  array('id' => '6206','nama' => 'KAB. KATINGAN'),
  array('id' => '6207','nama' => 'KAB. SERUYAN'),
  array('id' => '6208','nama' => 'KAB. SUKAMARA'),
  array('id' => '6209','nama' => 'KAB. LAMANDAU'),
  array('id' => '6210','nama' => 'KAB. GUNUNG MAS'),
  array('id' => '6211','nama' => 'KAB. PULANG PISAU'),
  array('id' => '6212','nama' => 'KAB. MURUNG RAYA'),
  array('id' => '6213','nama' => 'KAB. BARITO TIMUR'),
  array('id' => '6271','nama' => 'KOTA PALANGKARAYA'),
  array('id' => '6301','nama' => 'KAB. TANAH LAUT'),
  array('id' => '6302','nama' => 'KAB. KOTABARU'),
  array('id' => '6303','nama' => 'KAB. BANJAR'),
  array('id' => '6304','nama' => 'KAB. BARITO KUALA'),
  array('id' => '6305','nama' => 'KAB. TAPIN'),
  array('id' => '6306','nama' => 'KAB. HULU SUNGAI SELATAN'),
  array('id' => '6307','nama' => 'KAB. HULU SUNGAI TENGAH'),
  array('id' => '6308','nama' => 'KAB. HULU SUNGAI UTARA'),
  array('id' => '6309','nama' => 'KAB. TABALONG'),
  array('id' => '6310','nama' => 'KAB. TANAH BUMBU'),
  array('id' => '6311','nama' => 'KAB. BALANGAN'),
  array('id' => '6371','nama' => 'KOTA BANJARMASIN'),
  array('id' => '6372','nama' => 'KOTA BANJARBARU'),
  array('id' => '6401','nama' => 'KAB. PASER'),
  array('id' => '6402','nama' => 'KAB. KUTAI KARTANEGARA'),
  array('id' => '6403','nama' => 'KAB. BERAU'),
  array('id' => '6407','nama' => 'KAB. KUTAI BARAT'),
  array('id' => '6408','nama' => 'KAB. KUTAI TIMUR'),
  array('id' => '6409','nama' => 'KAB. PENAJAM PASER UTARA'),
  array('id' => '6411','nama' => 'KAB. MAHAKAM ULU'),
  array('id' => '6471','nama' => 'KOTA BALIKPAPAN'),
  array('id' => '6472','nama' => 'KOTA SAMARINDA'),
  array('id' => '6474','nama' => 'KOTA BONTANG'),
  array('id' => '6501','nama' => 'KAB. BULUNGAN'),
  array('id' => '6502','nama' => 'KAB. MALINAU'),
  array('id' => '6503','nama' => 'KAB. NUNUKAN'),
  array('id' => '6504','nama' => 'KAB. TANA TIDUNG'),
  array('id' => '6571','nama' => 'KOTA TARAKAN'),
  array('id' => '7101','nama' => 'KAB. BOLAANG MONGONDOW'),
  array('id' => '7102','nama' => 'KAB. MINAHASA'),
  array('id' => '7103','nama' => 'KAB. KEPULAUAN SANGIHE'),
  array('id' => '7104','nama' => 'KAB. KEPULAUAN TALAUD'),
  array('id' => '7105','nama' => 'KAB. MINAHASA SELATAN'),
  array('id' => '7106','nama' => 'KAB. MINAHASA UTARA'),
  array('id' => '7107','nama' => 'KAB. MINAHASA TENGGARA'),
  array('id' => '7108','nama' => 'KAB. BOLAANG MONGONDOW UTARA'),
  array('id' => '7109','nama' => 'KAB. KEP. SIAU TAGULANDANG BIARO'),
  array('id' => '7110','nama' => 'KAB. BOLAANG MONGONDOW TIMUR'),
  array('id' => '7111','nama' => 'KAB. BOLAANG MONGONDOW SELATAN'),
  array('id' => '7171','nama' => 'KOTA MANADO'),
  array('id' => '7172','nama' => 'KOTA BITUNG'),
  array('id' => '7173','nama' => 'KOTA TOMOHON'),
  array('id' => '7174','nama' => 'KOTA KOTAMOBAGU'),
  array('id' => '7201','nama' => 'KAB. BANGGAI'),
  array('id' => '7202','nama' => 'KAB. POSO'),
  array('id' => '7203','nama' => 'KAB. DONGGALA'),
  array('id' => '7204','nama' => 'KAB. TOLI TOLI'),
  array('id' => '7205','nama' => 'KAB. BUOL'),
  array('id' => '7206','nama' => 'KAB. MOROWALI'),
  array('id' => '7207','nama' => 'KAB. BANGGAI KEPULAUAN'),
  array('id' => '7208','nama' => 'KAB. PARIGI MOUTONG'),
  array('id' => '7209','nama' => 'KAB. TOJO UNA UNA'),
  array('id' => '7210','nama' => 'KAB. SIGI'),
  array('id' => '7211','nama' => 'KAB. BANGGAI LAUT'),
  array('id' => '7212','nama' => 'KAB. MOROWALI UTARA'),
  array('id' => '7271','nama' => 'KOTA PALU'),
  array('id' => '7301','nama' => 'KAB. KEPULAUAN SELAYAR'),
  array('id' => '7302','nama' => 'KAB. BULUKUMBA'),
  array('id' => '7303','nama' => 'KAB. BANTAENG'),
  array('id' => '7304','nama' => 'KAB. JENEPONTO'),
  array('id' => '7305','nama' => 'KAB. TAKALAR'),
  array('id' => '7306','nama' => 'KAB. GOWA'),
  array('id' => '7307','nama' => 'KAB. SINJAI'),
  array('id' => '7308','nama' => 'KAB. BONE'),
  array('id' => '7309','nama' => 'KAB. MAROS'),
  array('id' => '7310','nama' => 'KAB. PANGKAJENE KEPULAUAN'),
  array('id' => '7311','nama' => 'KAB. BARRU'),
  array('id' => '7312','nama' => 'KAB. SOPPENG'),
  array('id' => '7313','nama' => 'KAB. WAJO'),
  array('id' => '7314','nama' => 'KAB. SIDENRENG RAPPANG'),
  array('id' => '7315','nama' => 'KAB. PINRANG'),
  array('id' => '7316','nama' => 'KAB. ENREKANG'),
  array('id' => '7317','nama' => 'KAB. LUWU'),
  array('id' => '7318','nama' => 'KAB. TANA TORAJA'),
  array('id' => '7322','nama' => 'KAB. LUWU UTARA'),
  array('id' => '7324','nama' => 'KAB. LUWU TIMUR'),
  array('id' => '7326','nama' => 'KAB. TORAJA UTARA'),
  array('id' => '7371','nama' => 'KOTA MAKASSAR'),
  array('id' => '7372','nama' => 'KOTA PARE PARE'),
  array('id' => '7373','nama' => 'KOTA PALOPO'),
  array('id' => '7401','nama' => 'KAB. KOLAKA'),
  array('id' => '7402','nama' => 'KAB. KONAWE'),
  array('id' => '7403','nama' => 'KAB. MUNA'),
  array('id' => '7404','nama' => 'KAB. BUTON'),
  array('id' => '7405','nama' => 'KAB. KONAWE SELATAN'),
  array('id' => '7406','nama' => 'KAB. BOMBANA'),
  array('id' => '7407','nama' => 'KAB. WAKATOBI'),
  array('id' => '7408','nama' => 'KAB. KOLAKA UTARA'),
  array('id' => '7409','nama' => 'KAB. KONAWE UTARA'),
  array('id' => '7410','nama' => 'KAB. BUTON UTARA'),
  array('id' => '7411','nama' => 'KAB. KOLAKA TIMUR'),
  array('id' => '7412','nama' => 'KAB. KONAWE KEPULAUAN'),
  array('id' => '7413','nama' => 'KAB. MUNA BARAT'),
  array('id' => '7414','nama' => 'KAB. BUTON TENGAH'),
  array('id' => '7415','nama' => 'KAB. BUTON SELATAN'),
  array('id' => '7471','nama' => 'KOTA KENDARI'),
  array('id' => '7472','nama' => 'KOTA BAU BAU'),
  array('id' => '7501','nama' => 'KAB. GORONTALO'),
  array('id' => '7502','nama' => 'KAB. BOALEMO'),
  array('id' => '7503','nama' => 'KAB. BONE BOLANGO'),
  array('id' => '7504','nama' => 'KAB. PAHUWATO'),
  array('id' => '7505','nama' => 'KAB. GORONTALO UTARA'),
  array('id' => '7571','nama' => 'KOTA GORONTALO'),
  array('id' => '7601','nama' => 'KAB. MAMUJU UTARA'),
  array('id' => '7602','nama' => 'KAB. MAMUJU'),
  array('id' => '7603','nama' => 'KAB. MAMASA'),
  array('id' => '7604','nama' => 'KAB. POLEWALI MANDAR'),
  array('id' => '7605','nama' => 'KAB. MAJENE'),
  array('id' => '7606','nama' => 'KAB. MAMUJU TENGAH'),
  array('id' => '8101','nama' => 'KAB. MALUKU TENGAH'),
  array('id' => '8102','nama' => 'KAB. MALUKU TENGGARA'),
  array('id' => '8103','nama' => 'KAB. MALUKU TENGGARA BARAT'),
  array('id' => '8104','nama' => 'KAB. BURU'),
  array('id' => '8105','nama' => 'KAB. SERAM BAGIAN TIMUR'),
  array('id' => '8106','nama' => 'KAB. SERAM BAGIAN BARAT'),
  array('id' => '8107','nama' => 'KAB. KEPULAUAN ARU'),
  array('id' => '8108','nama' => 'KAB. MALUKU BARAT DAYA'),
  array('id' => '8109','nama' => 'KAB. BURU SELATAN'),
  array('id' => '8171','nama' => 'KOTA AMBON'),
  array('id' => '8172','nama' => 'KOTA TUAL'),
  array('id' => '8201','nama' => 'KAB. HALMAHERA BARAT'),
  array('id' => '8202','nama' => 'KAB. HALMAHERA TENGAH'),
  array('id' => '8203','nama' => 'KAB. HALMAHERA UTARA'),
  array('id' => '8204','nama' => 'KAB. HALMAHERA SELATAN'),
  array('id' => '8205','nama' => 'KAB. KEPULAUAN SULA'),
  array('id' => '8206','nama' => 'KAB. HALMAHERA TIMUR'),
  array('id' => '8207','nama' => 'KAB. PULAU MOROTAI'),
  array('id' => '8208','nama' => 'KAB. PULAU TALIABU'),
  array('id' => '8271','nama' => 'KOTA TERNATE'),
  array('id' => '8272','nama' => 'KOTA TIDORE KEPULAUAN'),
  array('id' => '9101','nama' => 'KAB. MERAUKE'),
  array('id' => '9102','nama' => 'KAB. JAYAWIJAYA'),
  array('id' => '9103','nama' => 'KAB. JAYAPURA'),
  array('id' => '9104','nama' => 'KAB. NABIRE'),
  array('id' => '9105','nama' => 'KAB. KEPULAUAN YAPEN'),
  array('id' => '9106','nama' => 'KAB. BIAK NUMFOR'),
  array('id' => '9107','nama' => 'KAB. PUNCAK JAYA'),
  array('id' => '9108','nama' => 'KAB. PANIAI'),
  array('id' => '9109','nama' => 'KAB. MIMIKA'),
  array('id' => '9110','nama' => 'KAB. SARMI'),
  array('id' => '9111','nama' => 'KAB. KEEROM'),
  array('id' => '9112','nama' => 'KAB. PEGUNUNGAN BINTANG'),
  array('id' => '9113','nama' => 'KAB. YAHUKIMO'),
  array('id' => '9114','nama' => 'KAB. TOLIKARA'),
  array('id' => '9115','nama' => 'KAB. WAROPEN'),
  array('id' => '9116','nama' => 'KAB. BOVEN DIGOEL'),
  array('id' => '9117','nama' => 'KAB. MAPPI'),
  array('id' => '9118','nama' => 'KAB. ASMAT'),
  array('id' => '9119','nama' => 'KAB. SUPIORI'),
  array('id' => '9120','nama' => 'KAB. MAMBERAMO RAYA'),
  array('id' => '9121','nama' => 'KAB. MAMBERAMO TENGAH'),
  array('id' => '9122','nama' => 'KAB. YALIMO'),
  array('id' => '9123','nama' => 'KAB. LANNY JAYA'),
  array('id' => '9124','nama' => 'KAB. NDUGA'),
  array('id' => '9125','nama' => 'KAB. PUNCAK'),
  array('id' => '9126','nama' => 'KAB. DOGIYAI'),
  array('id' => '9127','nama' => 'KAB. INTAN JAYA'),
  array('id' => '9128','nama' => 'KAB. DEIYAI'),
  array('id' => '9171','nama' => 'KOTA JAYAPURA'),
  array('id' => '9201','nama' => 'KAB. SORONG'),
  array('id' => '9202','nama' => 'KAB. MANOKWARI'),
  array('id' => '9203','nama' => 'KAB. FAK FAK'),
  array('id' => '9204','nama' => 'KAB. SORONG SELATAN'),
  array('id' => '9205','nama' => 'KAB. RAJA AMPAT'),
  array('id' => '9206','nama' => 'KAB. TELUK BINTUNI'),
  array('id' => '9207','nama' => 'KAB. TELUK WONDAMA'),
  array('id' => '9208','nama' => 'KAB. KAIMANA'),
  array('id' => '9209','nama' => 'KAB. TAMBRAUW'),
  array('id' => '9210','nama' => 'KAB. MAYBRAT'),
  array('id' => '9211','nama' => 'KAB. MANOKWARI SELATAN'),
  array('id' => '9212','nama' => 'KAB. PEGUNUNGAN ARFAK'),
  array('id' => '9271','nama' => 'KOTA SORONG')
);
